Parameters:
  ConditionTagKey:
    Type: String
    Default: ManagedByPipeline

Resources:

  #----- Roles ----

  PipelineIAMAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - cloudformation.amazonaws.com
      Description: Pipeline Administration Role
      MaxSessionDuration: 3600
      RoleName: PipelineIAMAdminRole
      Tags:
        - Key: !Ref ConditionTagKey
          Value: 'true'

  PipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 
              - sts:AssumeRole
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Description: Pipeline Execution Role
      MaxSessionDuration: 3600
      RoleName: PipelineExecutionRole
      Tags:
        - Key: ConditionTagKey
          Value: 'true'

  PipelineAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - cloudformation.amazonaws.com
      Description: Pipeline Administration Role
      MaxSessionDuration: 3600
      RoleName: PipelineAdminRole
      Tags:
        - Key: ConditionTagKey
          Value: 'true'

  #----- Policies -----

  PipelineIAMAdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PipelineIAMAdminPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: 
              - iam:*
            Resource: '*'
            Condition:
              StringEquals: 
                !Sub 'iam:ResourceTag/${ConditionTagKey}': 'true' 
      Roles:
        - !Ref PipelineIAMAdminRole

  PipelineAdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PipelineAdminPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:UpdatePipeline
              - codepipeline:StartPipelineExecution
              - codepipeline:DeletePipeline
              - codepipeline:DeregisterWebhookWithThirdParty
              - codepipeline:GetPipeline
            Resource: '*'
            Condition:
              StringEquals: 
                !Sub 'iam:ResourceTag/${ConditionTagKey}': 'true' 
          - Effect: Allow
            Action: 
              - ssm:GetParameters
              - codepipeline:UpdatePipeline
              - codepipeline:StartPipelineExecution
              - codepipeline:DeletePipeline
              - codepipeline:DeregisterWebhookWithThirdParty
              - codepipeline:GetPipeline
              - codepipeline:DeleteWebhook
              - s3:DeleteBucket
              - s3:DeleteBucketPolicy
            Resource: '*'
            Condition:
              StringEquals: 
                !Sub 'iam:ResourceTag/${ConditionTagKey}': 'true' 
          - Effect: Allow
            Action: 
              - iam:PassRole
            Resource: '*'
            Condition:
              StringEquals: 
                !Sub 'iam:ResourceTag/${ConditionTagKey}': 'true' 
          - Effect: Allow
            Action: codepipeline:DeregisterWebhookWithThirdParty
            Resource: '*'
      Roles:
        - !Ref PipelineAdminRole

  PipelineExecutionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PipelineExecutionRolePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: 
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
            Resource: '*'
            Condition:
              StringEquals: 
                !Sub 'iam:ResourceTag/${ConditionTagKey}': 'true' 
          - Effect: Allow
            Action: 
              - iam:PassRole
            Resource: '*'
            Condition:
              StringEquals: 
                !Sub 'iam:ResourceTag/${ConditionTagKey}': 'true' 
      Roles:
        - !Ref PipelineExecutionRole

Outputs:
  PipelineIAMAdminRoleArn:
    Description: ARN of IAM role to Administer the IAM Stack
    Value: !GetAtt PipelineIAMAdminRole.Arn
    Export:
      Name: PipelineIAMAdminRoleArn
  
  PipelineExecutionRole:
    Description: ARN of IAM role to Execute the CodePipeline
    Value: !Ref PipelineExecutionRole
    Export:
      Name: PipelineExecutionRole

  PipelineExecutionRoleArn:
    Description: ARN of IAM role to Execute the CodePipeline
    Value: !GetAtt PipelineExecutionRole.Arn
    Export:
      Name: PipelineExecutionRoleArn

  PipelineAdminRoleArn:
    Description: ARN of IAM role to Administer the CodePipeline
    Value: !GetAtt PipelineAdminRole.Arn
    Export:
      Name: PipelineAdminRoleArn