Parameters:
  GHToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: token
  
  TriggerBranch:
    Type: String
    Default: master

  IAMStackName:
    Type: String
    Default: IAMStack

  ConditionTagKey:
    Type: String
    Default: ManagedByPipeline

Resources:

  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: GHToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetAction: Source
      TargetPipeline: !Ref Pipeline
      TargetPipelineVersion: 1
      RegisterWithThirdParty: true

#----- IAM -----

  PipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 
              - sts:AssumeRole
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Description: Pipeline Execution Role
      MaxSessionDuration: 3600
      RoleName: PipelineExecutionRole
      Tags:
        - Key: ManagedByPipeline
          Value: 'true'

  PipelineAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - cloudformation.amazonaws.com
      Description: Pipeline Administration Role
      MaxSessionDuration: 3600
      RoleName: PipelineAdminRole
      Tags:
        - Key: ManagedByPipeline
          Value: 'true'

  PipelineAdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PipelineAdminPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:DeleteWebhook
              - codepipeline:DeregisterWebhookWithThirdParty
              - codepipeline:UpdatePipeline
              - codepipeline:StartPipelineExecution
              - codepipeline:DeletePipeline
              - codepipeline:GetPipeline
            Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}"
          - Effect: Allow
            Action:
              - s3:DeleteBucket
              - s3:DeleteBucketPolicy
            Resource: !GetAtt ArtifactBucket.Arn
          - Effect: Allow
            Action: 
              - iam:PassRole
              - ssm:GetParameters
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: !GetAtt PipelineAdminRole.Arn
          - Effect: Allow
            Action: 
              - iam:*
            Resource: 
              - !GetAtt PipelineAdminRole.Arn
              - !GetAtt PipelineExecutionRole.Arn
      Roles:
        - !Ref PipelineAdminRole

  PipelineExecutionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PipelineExecutionRolePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: 
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
            Resource: !Ref AWS::StackId
          - Effect: Allow
            Action: 
              - iam:PassRole
            Resource: !GetAtt PipelineExecutionRole.Arn
      Roles:
        - !Ref PipelineExecutionRole

#----------Pipeline------------

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: DemoPipeline
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt PipelineExecutionRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                  Owner: ZhangMaKe
                  Repo: AWSSelfUpdatingPipeline
                  Branch: !Ref TriggerBranch
                  OAuthToken: !Ref GHToken
              OutputArtifacts:
                - Name: infra-source
        - Name: Administration
          Actions:
            # - Name: AdministerIAM
            #   ActionTypeId:
            #       Category: Deploy
            #       Owner: AWS
            #       Provider: CloudFormation
            #       Version: '1'
            #   Configuration:
            #     OutputFileName: iamStackOutput.json
            #     Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
            #     RoleArn: !ImportValue PipelineIAMAdminRoleArn
            #     StackName: !Ref IAMStackName
            #     ActionMode: CREATE_UPDATE
            #     TemplatePath: infra-source::iam.yml
            #   InputArtifacts:
            #     - Name: infra-source
            #   RunOrder: 1
            - Name: AdministerPipeline
              ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
              Configuration:
                OutputFileName: pipelineStackOutput.json
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt PipelineAdminRole.Arn
                StackName: !Ref AWS::StackName
                ActionMode: CREATE_UPDATE
                TemplatePath: infra-source::pipeline.yml
              InputArtifacts:
                - Name: infra-source
              RunOrder: 2
      ArtifactStores:
        - ArtifactStore:
            Location: !Ref ArtifactBucket
            Type: S3
          Region: us-east-1
      Tags:
        - Key: ManagedByPipeline
          Value: 'true'

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: ManagedByPipeline
          Value: 'true'

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref ArtifactBucket
      PolicyDocument: 
        Statement: 
        - 
          Action: 
            - s3:GetObject
            - s3:PutObject
          Effect: "Allow"
          Resource: !Sub "arn:aws:s3:::${ArtifactBucket}/*"
          Principal: 
            AWS: 
              - !ImportValue PipelineExecutionRoleArn

