Parameters:
  GHToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: token
  
  TriggerBranch:
    Type: String
    Default: master

  IAMStackName:
    Type: String
    Default: IAMStack

Resources:

  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: GHToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetAction: Source
      TargetPipeline: !Ref Pipeline
      TargetPipelineVersion: 1
      RegisterWithThirdParty: true

#----------Pipeline------------

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: DemoPipeline
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue PipelineExecutionRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                  Owner: ZhangMaKe
                  Repo: AWSSelfUpdatingPipeline
                  Branch: !Ref TriggerBranch
                  OAuthToken: !Ref GHToken
              OutputArtifacts:
                - Name: infra-source
        - Name: AdministerIAM
          Actions:
            - Name: AdministerIAM
              ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
              Configuration:
                OutputFileName: iamStackOutput.json
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !ImportValue PipelineIAMAdminRoleArn
                StackName: !Ref IAMStackName
                ActionMode: CREATE_UPDATE
                TemplatePath: infra-source::iam.yml
              InputArtifacts:
                - Name: infra-source
              RunOrder: 1
            - Name: AdministerPipeline
              ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
              Configuration:
                OutputFileName: pipelineStackOutput.json
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !ImportValue PipelineAdminRoleArn
                StackName: !Ref AWS::StackName
                ActionMode: CREATE_UPDATE
                TemplatePath: infra-source::pipeline.yml
              InputArtifacts:
                - Name: infra-source
              RunOrder: 2
      ArtifactStores:
        - ArtifactStore:
            Location: !Ref ArtifactBucket
            Type: S3
          Region: us-east-1
      Tags:
        - Key: ManagedByPipeline
          Value: 'true'

  ArtifactBucket:
    Type: AWS::S3::Bucket

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref ArtifactBucket
      PolicyDocument: 
        Statement: 
        - 
          Action: 
            - s3:GetObject
            - s3:PutObject
          Effect: "Allow"
          Resource: !Sub "arn:aws:s3:::${ArtifactBucket}/*"
          Principal: 
            AWS: 
              - !ImportValue PipelineExecutionRoleArn
        - 
          Action: 
            - s3:DeleteBucket
            - s3:DeleteBucketPolicy
          Effect: "Allow"
          Resource: !Sub "arn:aws:s3:::${ArtifactBucket}"
          Principal: 
            AWS: 
              - !ImportValue PipelineAdminRoleArn

